### ISSUE TITLE
Incorrect unit on divider for SPF

### ISSUE THREAD

**Issue by goandfix** [muppet3000/homeassistant-grott#67]
Hi I'm not sure if it happens with the other units of gorwatt but I have SPF3000 and the unit to meassure in the all current section I had to change it per divider 10 instead 100 and into the load percentage I changed it from 1 to 10. Thanks!

**Comment by muppet3000** [comment]
Hi @goandfix  - Can you please try running from the `main` version of the integration. I believe I've already fixed this for SPF systems, I just haven't done the formal release yet.

**Comment by goandfix** [comment]
Nop it's still wrong:

![sensorfix](https://github.com/muppet3000/homeassistant-grott/assets/32076332/e67bb38f-c90b-4221-a2fa-bd4892643659)

In the left side is your file hosted in the github and in the right side is the value that I already fixed on my local installation.

**Comment by muppet3000** [comment]
Thanks @goandfix  - is it just those two that you've highlighted, I didn't realise you were referring to 'current' as in the power unit, I thought you meant that the current version on main was all wrong.
Thanks for the zip, I'll do a diff, but if it's just the changes in the screengrab I can change those no problem.

**Comment by goandfix** [comment]
It's my pleaseure my friend to help you!

**Comment by muppet3000** [comment]
I've just pushed a fix with '
